name: Build EXE with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest   # Windows 才能編譯 .exe

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka numpy pandas scipy matplotlib

      - name: Build exe
        run: |
          python -m nuitka main.py --standalone --onefile --enable-plugin=numpy --enable-plugin=matplotlib --enable-plugin=tk-inter|PySide6|PySide2|PyQt6|PyQt5 -j 4 --output-dir=dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: f-tool-exe
          path: dist/
